backend:
  name: github
  repo: Jeff1059/wwwKreyasion
  branch: main
  base_url: https://www.kreyasion-design.fr
  auth_endpoint: api/auth/auth
  auth_callback_endpoint: api/auth/callback

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Mes Pages"
    files:
      - label: "Accueil"
        name: "index"
        file: "index.html"
        fields:
          - {label: "Titre principal", name: "title", widget: "string"}
          - {label: "Contenu", name: "body", widget: "markdown"}
